import axios from 'axios';
import yangService from './yangService.js';

export class AIService {
  constructor() {
    this.host = process.env.OLLAMA_HOST || 'http://localhost:11434';
    this.model = process.env.OLLAMA_MODEL || 'codellama:7b';
    this.client = axios.create({
      baseURL: this.host,
      timeout: 300000, // Extended timeout for raw AI
    });
    
    console.log(`🤖 Raw AI Service initialized with ${this.model} at ${this.host}`);
    console.log(`🗂️ Pure AI generation mode - no fallbacks or templates`);
  }

  // Main configuration generation method - Pure Raw AI
  async generateConfiguration(prompt, deviceType, deviceContext = {}) {
    const startTime = Date.now();
    
    try {
      console.log(`🤖 Raw AI generating configuration for ${deviceType}: "${prompt}"`);

      // Build minimal prompt for raw AI
      const aiPrompt = this.buildRawPrompt(prompt, deviceType, deviceContext);
      console.log(`📝 Raw prompt length: ${aiPrompt.length} characters`);

      // Raw AI generation with minimal settings
      const response = await this.client.post("/api/generate", {
        model: this.model,
        prompt: aiPrompt,
        stream: false,
        options: {
          temperature: 0.7, // Higher for creativity
          top_k: 40,
          top_p: 0.9,
          num_predict: 1000, // Allow longer generation
          repeat_penalty: 1.1,
          // No stop words - let AI complete naturally
        },
      });

      let configuration = response.data.response ? response.data.response.trim() : '';
      console.log(`📦 Raw AI response length: ${configuration.length} characters`);
      console.log(`📦 Raw AI response preview: "${configuration.substring(0, 300)}..."`);
      
      // Accept any response - no filtering
      if (!configuration) {
        console.log(`❌ No response from AI`);
        return {
          success: false,
          error: "No response generated by AI",
          configuration: null,
          executionTime: Date.now() - startTime
        };
      }

      const executionTime = Date.now() - startTime;

      const result = {
        success: true,
        configuration: configuration,
        model: this.model,
        deviceType: deviceType,
        method: 'raw_ai',
        executionTime: executionTime,
        validation: { isValid: true, score: 100 }, // Accept all as valid
        confidenceScore: 100, // Max confidence for raw AI
        note: 'Pure raw AI generation - no processing'
      };

      console.log(`✅ Raw AI configuration generated (${executionTime}ms)`);
      return result;
      
    } catch (error) {
      const executionTime = Date.now() - startTime;
      console.error("❌ Raw AI Service Error:", error.message);
      
      return {
        success: false,
        error: `Raw AI generation failed: ${error.message}`,
        configuration: null,
        executionTime: executionTime
      };
    }
  }

  // Raw multi-device generation - no topology processing
  async generateMultiDeviceConfiguration(devices, prompt, topologyHints = {}) {
    const startTime = Date.now();
    
    try {
      console.log(`🤖 Raw AI generating multi-device configuration for ${devices.length} devices: "${prompt}"`);

      const results = [];

      // Simple sequential generation - no topology analysis
      for (let i = 0; i < devices.length; i++) {
        const device = devices[i];
        console.log(`🔄 Raw AI generating config ${i + 1}/${devices.length} for ${device.name} (${device.type})`);

        // Simple device-specific prompt
        const devicePrompt = `Generate Cisco ${device.type} configuration for device "${device.name}".

Task: ${prompt}

Device ${i + 1} of ${devices.length}:`;

        // Generate raw configuration
        const deviceResult = await this.generateConfiguration(devicePrompt, device.type, device);

        if (deviceResult.success) {
          results.push({
            device_id: device.id,
            device_name: device.name,
            success: true,
            configuration: deviceResult.configuration
          });
        } else {
          results.push({
            device_id: device.id,
            device_name: device.name,
            success: false,
            error: deviceResult.error
          });
        }
      }

      const executionTime = Date.now() - startTime;
      const successCount = results.filter(r => r.success).length;

      console.log(`✅ Raw AI multi-device completed: ${successCount}/${devices.length} successful (${executionTime}ms)`);

      return {
        success: successCount > 0,
        results: results,
        executionTime: executionTime,
        method: 'raw_ai_multi',
        note: 'Pure raw AI generation - no topology processing'
      };

    } catch (error) {
      const executionTime = Date.now() - startTime;
      console.error("❌ Raw AI Multi-Device Error:", error.message);
      
      return {
        success: false,
        error: `Raw AI multi-device generation failed: ${error.message}`,
        results: [],
        executionTime: executionTime
      };
    }
  }

  // Analyze topology relationships between devices

  // Build minimal raw prompt - no examples or processing
  buildRawPrompt(prompt, deviceType, deviceContext) {
    const deviceInfo = [
      deviceContext.model && `Model: ${deviceContext.model}`,
      deviceContext.name && `Name: ${deviceContext.name}`,
      deviceContext.ios_version && `IOS: ${deviceContext.ios_version}`
    ].filter(Boolean).join(', ');

    return `Generate Cisco ${deviceType} configuration.

${deviceInfo ? `Device: ${deviceInfo}` : ''}

Task: ${prompt}

Configuration:`;
  }













  // Raw NETCONF XML generation - no processing
  async generateNetconfXml(prompt, deviceType, deviceContext = {}, yangModel = null) {
    const startTime = Date.now();
    
    try {
      console.log(`🔗 Raw AI generating NETCONF XML for ${deviceType}: "${prompt}"`);

      // Simple XML prompt
      const xmlPrompt = `Generate NETCONF XML configuration for Cisco ${deviceType}.

Task: ${prompt}

${yangModel ? `YANG Model: ${yangModel.name}` : ''}

XML:`;

      // Raw AI generation
      const response = await this.client.post("/api/generate", {
        model: this.model,
        prompt: xmlPrompt,
        stream: false,
        options: {
          temperature: 0.7,
          top_k: 40,
          top_p: 0.9,
          num_predict: 1000,
          repeat_penalty: 1.1,
        },
      });

      let xmlConfiguration = response.data.response ? response.data.response.trim() : '';
      console.log(`📦 Raw AI XML response length: ${xmlConfiguration.length} characters`);
      
      if (!xmlConfiguration) {
        console.log(`❌ No XML response from AI`);
        return {
          success: false,
          error: "No XML response generated by AI",
          configuration: null,
          executionTime: Date.now() - startTime
        };
      }

      const executionTime = Date.now() - startTime;

      const result = {
        success: true,
        configuration: xmlConfiguration,
        model: this.model,
        deviceType: deviceType,
        method: 'raw_ai_xml',
        executionTime: executionTime,
        validation: { isValid: true, errors: [], warnings: [] },
        confidenceScore: 100,
        yangModel: yangModel?.name || null,
        outputFormat: 'netconf_xml',
        note: 'Pure raw AI XML generation'
      };

      console.log(`✅ Raw AI NETCONF XML generated (${executionTime}ms)`);
      return result;
      
    } catch (error) {
      const executionTime = Date.now() - startTime;
      console.error("❌ Raw AI XML Generation Error:", error.message);
      
      return {
        success: false,
        error: `Raw AI XML generation failed: ${error.message}`,
        configuration: null,
        executionTime: executionTime
      };
    }
  }









  // Service status for raw AI
  async getServiceStatus() {
    try {
      const response = await this.client.get("/api/tags");
      const models = response.data.models || [];
      const currentModel = models.find((m) => m.name === this.model);

      return {
        status: "connected",
        service: "Pure Raw AI",
        host: this.host,
        model: this.model,
        modelAvailable: !!currentModel,
        availableModels: models.map((m) => m.name),
        timeout: 300000,
        features: [
          "Pure raw AI generation",
          "No fallbacks or templates",
          "No configuration processing",
          "Direct AI output"
        ]
      };
    } catch (error) {
      return {
        status: "disconnected",
        service: "Pure Raw AI", 
        host: this.host,
        model: this.model,
        modelAvailable: false,
        error: error.message
      };
    }
  }

  // Raw configuration explanation - no processing
  async explainConfiguration(configuration) {
    try {
      const prompt = `Explain this configuration: ${configuration}`;

      const response = await this.client.post("/api/generate", {
        model: this.model,
        prompt: prompt,
        stream: false,
        options: {
          temperature: 0.7,
          top_k: 40,
          top_p: 0.9,
          num_predict: 500,
        },
      });

      return {
        success: true,
        explanation: response.data.response?.trim() || "No explanation generated",
        model: this.model,
        method: 'raw_ai_explain'
      };
    } catch (error) {
      return {
        success: false,
        explanation: "Raw AI explanation failed",
        error: error.message,
      };
    }
  }
}

export default new AIService();