import axios from 'axios';
import yangService from './yangService.js';
import aiContext from './aiContext.js';

export class AIService {
  constructor() {
    this.host = process.env.OLLAMA_HOST || 'http://localhost:11434';
    this.model = process.env.OLLAMA_MODEL || 'qwen2.5-coder:3b';
    this.client = axios.create({
      baseURL: this.host,
      timeout: 300000, // Extended timeout for raw AI
    });
    
    console.log(`🤖 AI Service initialized with ${this.model} at ${this.host}`);
    console.log(`🔧 Plain configuration generation - OSPF, EIGRP, RIPv2, BGP, ISIS supported`);
  }

  // Main configuration generation method
  async generateConfiguration(prompt, deviceType, deviceContext = {}) {
    const startTime = Date.now();
    
    try {
      console.log(`🤖 AI generating configuration for ${deviceType}: "${prompt}"`);

      // Check if prompt contains CIDR notation
      const cidrRegex = /\/\d{1,2}/g;
      const hasCIDR = cidrRegex.test(prompt);
      if (hasCIDR) {
        console.log(`🔧 CIDR notation detected - will convert to wildcard mask`);
      }

      // Build prompt using AI Context
      const aiPrompt = aiContext.buildConfigurationPrompt(prompt, deviceType, deviceContext);
      console.log(`📝 Prompt length: ${aiPrompt.length} characters`);

      // AI generation
      const response = await this.client.post("/api/generate", {
        model: this.model,
        prompt: aiPrompt,
        stream: false,
        options: {
          temperature: 0.3, // Lower temperature for more consistent configuration output
          top_k: 40,
          top_p: 0.9,
          num_predict: 1000, // Allow longer generation
          repeat_penalty: 1.1,
        },
      });

      let configuration = response.data.response ? response.data.response.trim() : '';
      console.log(`📦 AI response length: ${configuration.length} characters`);
      
      // Clean the response using AI Context
      if (configuration) {
        const originalLength = configuration.length;
        configuration = aiContext.cleanConfigurationResponse(configuration);
        console.log(`🧹 Cleaned response: ${originalLength} → ${configuration.length} characters`);
      }
      
      console.log(`📦 Final config preview: "${configuration.substring(0, 200)}..."`);
      
      if (!configuration) {
        console.log(`❌ No valid configuration commands found`);
        return {
          success: false,
          error: "No valid configuration commands generated by AI",
          configuration: null,
          executionTime: Date.now() - startTime
        };
      }

      const executionTime = Date.now() - startTime;

      const result = {
        success: true,
        configuration: configuration,
        model: this.model,
        deviceType: deviceType,
        method: 'ai_with_context',
        executionTime: executionTime,
        validation: { isValid: true, score: 100 },
        confidenceScore: 100,
        note: 'AI generation with CIDR conversion and context cleaning (OSPF, EIGRP, RIPv2, BGP, ISIS supported)'
      };

      console.log(`✅ AI configuration generated (${executionTime}ms)${hasCIDR ? ' with CIDR conversion' : ''}`);
      return result;
      
    } catch (error) {
      const executionTime = Date.now() - startTime;
      console.error("❌ AI Service Error:", error.message);
      
      return {
        success: false,
        error: `AI generation failed: ${error.message}`,
        configuration: null,
        executionTime: executionTime
      };
    }
  }

  // Multi-device generation using AI Context
  async generateMultiDeviceConfiguration(devices, prompt, topologyHints = {}) {
    const startTime = Date.now();
    
    try {
      console.log(`🤖 AI generating multi-device configuration for ${devices.length} devices: "${prompt}"`);

      const results = [];

      // Sequential generation using AI Context
      for (let i = 0; i < devices.length; i++) {
        const device = devices[i];
        console.log(`🔄 AI generating config ${i + 1}/${devices.length} for ${device.name} (${device.type})`);

        // Build device-specific prompt using AI Context
        const devicePrompt = aiContext.buildMultiDevicePrompt(prompt, device, i, devices.length);

        // Generate configuration using main method
        const deviceResult = await this.generateConfiguration(devicePrompt, device.type, device);

        if (deviceResult.success) {
          results.push({
            device_id: device.id,
            device_name: device.name,
            success: true,
            configuration: deviceResult.configuration
          });
        } else {
          results.push({
            device_id: device.id,
            device_name: device.name,
            success: false,
            error: deviceResult.error
          });
        }
      }

      const executionTime = Date.now() - startTime;
      const successCount = results.filter(r => r.success).length;

      console.log(`✅ AI multi-device completed: ${successCount}/${devices.length} successful (${executionTime}ms)`);

      return {
        success: successCount > 0,
        results: results,
        executionTime: executionTime,
        method: 'ai_multi_context',
        note: 'Multi-device AI generation with context and CIDR conversion'
      };

    } catch (error) {
      const executionTime = Date.now() - startTime;
      console.error("❌ AI Multi-Device Error:", error.message);
      
      return {
        success: false,
        error: `AI multi-device generation failed: ${error.message}`,
        results: [],
        executionTime: executionTime
      };
    }
  }

  // Analyze topology relationships between devices

  // NETCONF XML generation using AI Context
  async generateNetconfXml(prompt, deviceType, deviceContext = {}, yangModel = null) {
    const startTime = Date.now();
    
    try {
      console.log(`🔗 AI generating NETCONF XML for ${deviceType}: "${prompt}"`);

      // Build XML prompt using AI Context
      const xmlPrompt = aiContext.buildNetconfXmlPrompt(prompt, deviceType, yangModel);

      // AI generation
      const response = await this.client.post("/api/generate", {
        model: this.model,
        prompt: xmlPrompt,
        stream: false,
        options: {
          temperature: 0.3, // Lower temperature for more consistent XML format
          top_k: 40,
          top_p: 0.9,
          num_predict: 1000,
          repeat_penalty: 1.1,
        },
      });

      let xmlConfiguration = response.data.response ? response.data.response.trim() : '';
      console.log(`📦 AI XML response length: ${xmlConfiguration.length} characters`);
      
      // Clean XML response using AI Context
      if (xmlConfiguration) {
        const originalLength = xmlConfiguration.length;
        xmlConfiguration = aiContext.cleanXmlResponse(xmlConfiguration);
        console.log(`🧹 Cleaned XML: ${originalLength} → ${xmlConfiguration.length} characters`);
      }
      
      if (!xmlConfiguration) {
        console.log(`❌ No valid XML configuration found`);
        return {
          success: false,
          error: "No valid XML configuration generated by AI",
          configuration: null,
          executionTime: Date.now() - startTime
        };
      }

      const executionTime = Date.now() - startTime;

      const result = {
        success: true,
        configuration: xmlConfiguration,
        model: this.model,
        deviceType: deviceType,
        method: 'ai_xml_context',
        executionTime: executionTime,
        validation: { isValid: true, errors: [], warnings: [] },
        confidenceScore: 100,
        yangModel: yangModel?.name || null,
        outputFormat: 'netconf_xml',
        note: 'AI XML generation with context cleaning and CIDR conversion'
      };

      console.log(`✅ AI NETCONF XML generated (${executionTime}ms)`);
      return result;
      
    } catch (error) {
      const executionTime = Date.now() - startTime;
      console.error("❌ AI XML Generation Error:", error.message);
      
      return {
        success: false,
        error: `AI XML generation failed: ${error.message}`,
        configuration: null,
        executionTime: executionTime
      };
    }
  }









  // Service status for AI with context
  async getServiceStatus() {
    try {
      const response = await this.client.get("/api/tags");
      const models = response.data.models || [];
      const currentModel = models.find((m) => m.name === this.model);

      return {
        status: "connected",
        service: "AI Configuration Generator with Context",
        host: this.host,
        model: this.model,
        modelAvailable: !!currentModel,
        availableModels: models.map((m) => m.name),
        timeout: 300000,
        features: [
          "Context-based configuration generation",
          "CIDR to wildcard mask conversion",
          "Routing protocols: OSPF, EIGRP, RIPv2, BGP, ISIS",
          "Response cleaning and validation",
          "Multi-device support",
          "NETCONF XML generation"
        ]
      };
    } catch (error) {
      return {
        status: "disconnected",
        service: "AI Configuration Generator with Context", 
        host: this.host,
        model: this.model,
        modelAvailable: false,
        error: error.message
      };
    }
  }

  // Configuration explanation using context
  async explainConfiguration(configuration) {
    try {
      const prompt = `Explain this Cisco configuration in simple terms: ${configuration}`;

      const response = await this.client.post("/api/generate", {
        model: this.model,
        prompt: prompt,
        stream: false,
        options: {
          temperature: 0.7,
          top_k: 40,
          top_p: 0.9,
          num_predict: 500,
        },
      });

      return {
        success: true,
        explanation: response.data.response?.trim() || "No explanation generated",
        model: this.model,
        method: 'ai_explain_context'
      };
    } catch (error) {
      return {
        success: false,
        explanation: "AI explanation failed",
        error: error.message,
      };
    }
  }
}

export default new AIService();