import { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import { 
  TerminalIcon, 
  RefreshCwIcon,
  UsbIcon,
  BluetoothIcon,
  CableIcon,
  ChevronDownIcon
} from 'lucide-react';

function ConsoleConfiguration() {
  const [availablePorts, setAvailablePorts] = useState([]);
  const [selectedPort, setSelectedPort] = useState('');
  const [isPortDropdownOpen, setIsPortDropdownOpen] = useState(false);
  const portDropdownRef = useRef(null);
  const [connectionSettings, setConnectionSettings] = useState({
    baudRate: 9600,
    dataBits: 8,
    parity: 'none',
    stopBits: 1
  });
  const [isConnected, setIsConnected] = useState(false);
  const [deviceId, setDeviceId] = useState(''); // Auto-generated by backend
  const [configMode, setConfigMode] = useState('template'); // 'template' or 'custom'
  const [selectedTemplate, setSelectedTemplate] = useState('');
  const [templates, setTemplates] = useState({});
  const [templateVariables, setTemplateVariables] = useState({});
  const [customConfig, setCustomConfig] = useState('');
  const [configResults, setConfigResults] = useState(null);
  const [isLoading, setIsLoading] = useState(false);


  // New state for enhanced SSH configuration
  const [ipConfigMethod, setIpConfigMethod] = useState('manual'); // 'manual' or 'dhcp'

  // Function to convert CIDR prefix to subnet mask
  const cidrToSubnetMask = (prefix) => {
    const prefixNum = parseInt(prefix.replace('/', ''));
    if (isNaN(prefixNum) || prefixNum < 0 || prefixNum > 32) {
      return null;
    }
    
    const mask = (0xFFFFFFFF << (32 - prefixNum)) >>> 0;
    return [
      (mask >>> 24) & 0xFF,
      (mask >>> 16) & 0xFF,
      (mask >>> 8) & 0xFF,
      mask & 0xFF
    ].join('.');
  };

  // Function to detect if input is CIDR format and convert
  const processSubnetInput = (input) => {
    if (input.startsWith('/')) {
      const converted = cidrToSubnetMask(input);
      return converted || input;
    }
    return input;
  };

  // Function to calculate number of hosts from CIDR prefix
  const cidrToHostCount = (prefix) => {
    const prefixNum = parseInt(prefix.replace('/', ''));
    if (isNaN(prefixNum) || prefixNum < 0 || prefixNum > 32) {
      return 0;
    }
    
    // Special case for /31 - RFC 3021 allows 2 usable hosts (point-to-point)
    if (prefixNum === 31) {
      return 2;
    }
    
    // Special case for /32 - single host
    if (prefixNum === 32) {
      return 1;
    }
    
    // Standard calculation: total addresses minus network and broadcast
    const hostBits = 32 - prefixNum;
    const totalAddresses = Math.pow(2, hostBits);
    return totalAddresses - 2;
  };

  // Get port icon based on port type
  const getPortIcon = (port) => {
    const name = (port.friendlyName || '').toLowerCase();
    const manufacturer = (port.manufacturer || '').toLowerCase();
    
    if (name.includes('bluetooth') || manufacturer.includes('bluetooth')) {
      return <BluetoothIcon className="h-4 w-4 text-blue-500" />;
    }
    if (port.isUSB || name.includes('usb') || manufacturer.includes('usb') || 
        manufacturer.includes('ftdi') || manufacturer.includes('prolific') || 
        manufacturer.includes('silicon')) {
      return <UsbIcon className="h-4 w-4 text-green-500" />;
    }
    return <CableIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />;
  };

  // Get port type label
  const getPortTypeLabel = (port) => {
    const name = (port.friendlyName || '').toLowerCase();
    const manufacturer = (port.manufacturer || '').toLowerCase();
    
    if (name.includes('bluetooth') || manufacturer.includes('bluetooth')) {
      return 'Bluetooth';
    }
    if (port.isUSB || name.includes('usb') || manufacturer.includes('usb') || 
        manufacturer.includes('ftdi') || manufacturer.includes('prolific') || 
        manufacturer.includes('silicon')) {
      return 'USB';
    }
    return 'Serial';
  };

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (portDropdownRef.current && !portDropdownRef.current.contains(event.target)) {
        setIsPortDropdownOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  useEffect(() => {
    fetchAvailablePorts();
    fetchTemplates();
  }, []);

  const fetchAvailablePorts = async () => {
    try {
      const response = await axios.get('/console/ports');
      setAvailablePorts(response.data.ports || []);
    } catch (error) {
      console.error('❌ Error fetching serial ports:', error.response?.data?.message || error.message);
      toast.error('Failed to fetch serial ports: ' + (error.response?.data?.message || error.message));
    }
  };

  const fetchTemplates = async () => {
    try {
      const response = await axios.get('/console/templates');
      setTemplates(response.data.templates || {});
    } catch (error) {
      console.error('Error fetching templates:', error);
    }
  };

  const handleTestConnection = async () => {
    if (!selectedPort) {
      console.warn('⚠️ Please select a serial port');
      toast.error('Please select a serial port');
      return;
    }

    setIsLoading(true);
    const toastId = toast.loading('Testing console connection...');
    
    try {
      const response = await axios.post('/console/test', {
        deviceId: '', // Empty deviceId will be auto-generated by backend
        portPath: selectedPort,
        baudRate: connectionSettings.baudRate,
        dataBits: connectionSettings.dataBits,
        parity: connectionSettings.parity,
        stopBits: connectionSettings.stopBits
      });

      // Add null/undefined checks for nested properties
      if (response.data && response.data.test) {
        if (response.data.test.success) {
          console.log('✅ Console connection test successful!');
          console.log('Response:', response.data.test.output || response.data.test.message);
          toast.success('Console connection test successful!', { id: toastId });
        } else {
          console.warn('⚠️ Console connection test failed:');
          console.warn('Error:', response.data.test.message);
          toast.error(`Connection test failed: ${response.data.test.message}`, { id: toastId });
        }
      } else if (response.data && response.data.success !== undefined) {
        // Handle direct success response format
        if (response.data.success) {
          toast.success('Console connection test successful!', { id: toastId });
        } else {
          toast.error(`Connection test failed: ${response.data.message || 'Unknown error'}`, { id: toastId });
        }
      } else {
        console.error('Invalid response format:', response.data);
        toast.error('Connection test failed: Invalid response from server', { id: toastId });
      }
    } catch (error) {
      console.error('❌ Connection test failed:', error.response?.data?.message || error.message);
      toast.error(`Connection test failed: ${error.response?.data?.message || error.message}`, { id: toastId });
    } finally {
      setIsLoading(false);
    }
  };

  const handleConnect = async () => {
    if (!selectedPort) {
      console.warn('⚠️ Please select a port');
      toast.error('Please select a port');
      return;
    }

    setIsLoading(true);
    const toastId = toast.loading('Connecting to console...');
    
    try {
      const response = await axios.post('/console/connect', {
        deviceId: '', // Empty deviceId will be auto-generated by backend
        portPath: selectedPort,
        baudRate: connectionSettings.baudRate,
        dataBits: connectionSettings.dataBits,
        parity: connectionSettings.parity,
        stopBits: connectionSettings.stopBits
      });

      setIsConnected(true);
      setDeviceId(response.data.deviceId); // Store device ID from backend response
      console.log('✅ Console connected successfully!');
      toast.success(`Connected to console on ${selectedPort}!`, { id: toastId });
    } catch (error) {
      console.error('❌ Connection failed:', error.response?.data?.message || error.message);
      toast.error(`Connection failed: ${error.response?.data?.message || error.message}`, { id: toastId });
    } finally {
      setIsLoading(false);
    }
  };

  const handleDisconnect = async () => {
    setIsLoading(true);
    try {
      await axios.post('/console/disconnect', {
        deviceId: deviceId,
        portPath: selectedPort
      });
      setIsConnected(false);
      setDeviceId(''); // Clear device ID
      console.log('✅ Console disconnected successfully!');
      toast.success('Console disconnected successfully!');
    } catch (error) {
      console.error('❌ Disconnect failed:', error.response?.data?.message || error.message);
      toast.error(`Disconnect failed: ${error.response?.data?.message || error.message}`);
    } finally {
      setIsLoading(false);
    }
  };

  const handleTemplateChange = (templateKey) => {
    setSelectedTemplate(templateKey);
    if (templates[templateKey]) {
      // Extract variables from template
      const template = templates[templateKey].config;
      const variableMatches = template.match(/\{\{(\w+)\}\}/g) || [];
      const variables = {};
      
      variableMatches.forEach(match => {
        const varName = match.replace(/[{}]/g, '');
        // Set default values for common variables
        switch(varName) {
          case 'rsa_key_size':
            variables[varName] = '2048';
            break;
          case 'management_interface':
            variables[varName] = 'vlan1';
            break;
          case 'management_mask':
            variables[varName] = '/24';
            break;
          case 'domain':
            variables[varName] = 'company.local';
            break;
          case 'username':
            variables[varName] = 'admin';
            break;
          default:
            variables[varName] = '';
        }
      });
      
      // Add important variables that might not be in template but needed for UI
      if (!variables.management_ip) variables.management_ip = '';
      if (!variables.management_mask) variables.management_mask = '/24';
      
      // Add IP method variable
      variables.ip_method = ipConfigMethod;
      
      setTemplateVariables(variables);
    }
  };

  const handleVariableChange = (varName, value) => {
    setTemplateVariables(prev => ({
      ...prev,
      [varName]: value
    }));
  };

  const handleIPMethodChange = (method) => {
    setIpConfigMethod(method);
    // Update the ip_method variable
    setTemplateVariables(prev => ({
      ...prev,
      ip_method: method
    }));
  };

  const handleApplyConfiguration = async () => {
    if (!isConnected) {
      console.warn('⚠️ Please connect to console first');
      toast.error('Please connect to console first');
      return;
    }

    if (!deviceId) {
      toast.error('Please connect to console first');
      return;
    }

    if (configMode === 'template' && !selectedTemplate) {
      toast.error('Please select a template');
      return;
    }

    if (configMode === 'custom' && !customConfig) {
      toast.error('Please enter custom configuration');
      return;
    }

    setIsLoading(true);
    const toastId = toast.loading('Applying configuration...');

    
    try {
      let response;
      
      if (configMode === 'template') {
        // Apply template configuration
        response = await axios.post('/console/templates/apply', {
          templateKey: selectedTemplate,
          variables: templateVariables,
          deviceId: deviceId
        });
      } else {
        // Apply custom configuration
        response = await axios.post('/console/initial-config', {
          deviceId: deviceId,
          configCommands: customConfig
        });
      }

      setConfigResults(response.data.configuration);
      const summary = response.data.configuration.summary;
      
      console.log('✅ Configuration completed!');
      console.log('Summary:\n' +
            `✅ Successful: ${summary.successful}/${summary.totalCommands} commands\n` +
            `❌ Failed: ${summary.failed} commands\n` +
            `📊 Success rate: ${summary.successRate}%`);
      
      if (summary.successRate === 100) {
        toast.success(`Configuration deployed successfully! ${summary.successful}/${summary.totalCommands} commands executed.`, { id: toastId });
      } else {
        toast.error(`Configuration partially deployed: ${summary.successful}/${summary.totalCommands} commands successful (${summary.successRate}%)`, { id: toastId });
      }
      
    } catch (error) {
      console.error('❌ Configuration failed:', error.response?.data?.message || error.message);
      
      toast.error(`Configuration failed: ${error.response?.data?.message || error.message}`, { id: toastId });
    } finally {
      setIsLoading(false);
    }
  };


  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white flex items-center gap-3">
            <div className="p-2 bg-green-100 dark:bg-green-900/50 rounded-xl">
              <TerminalIcon className="h-7 w-7 text-green-600 dark:text-green-400" />
            </div>
            Console Configuration
          </h1>
          <p className="mt-2 text-gray-600 dark:text-gray-400">
            Manage device console connections and terminal access
          </p>
        </div>
        <button
          onClick={fetchAvailablePorts}
          disabled={isLoading}
          className="btn btn-secondary btn-md"
        >
          <RefreshCwIcon className={`h-4 w-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      {/* Connection Settings */}
      <div className="bg-white dark:bg-gray-800 shadow rounded-lg p-6">
        <h2 className="text-lg font-medium text-gray-900 dark:text-white mb-4">Serial Console Connection</h2>

        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          {/* Port Selection - Custom Dropdown with Icons */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Serial Port</label>
            <div className="relative" ref={portDropdownRef}>
              <button
                type="button"
                onClick={() => !isConnected && setIsPortDropdownOpen(!isPortDropdownOpen)}
                className={`w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-left flex items-center justify-between ${
                  isConnected ? 'bg-gray-100 dark:bg-gray-600 cursor-not-allowed' : 'bg-white dark:bg-gray-700 cursor-pointer'
                }`}
                disabled={isConnected}
              >
                {selectedPort ? (
                  <span className="flex items-center gap-2 text-gray-900 dark:text-white">
                    {getPortIcon(availablePorts.find(p => p.path === selectedPort) || {})}
                    <span>{availablePorts.find(p => p.path === selectedPort)?.friendlyName || selectedPort}</span>
                  </span>
                ) : (
                  <span className="text-gray-500 dark:text-gray-400">Select Port</span>
                )}
                <ChevronDownIcon className={`h-4 w-4 text-gray-500 dark:text-gray-400 transition-transform ${isPortDropdownOpen ? 'rotate-180' : ''}`} />
              </button>
              
              {isPortDropdownOpen && (
                <div className="absolute z-10 w-full mt-1 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-lg max-h-60 overflow-auto">
                  <div
                    className="px-3 py-2 cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-600 text-gray-500 dark:text-gray-400"
                    onClick={() => {
                      setSelectedPort('');
                      setIsPortDropdownOpen(false);
                    }}
                  >
                    Select Port
                  </div>
                  {availablePorts.map((port) => (
                    <div
                      key={port.path}
                      className={`px-3 py-2 cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-600 flex items-center gap-2 ${
                        selectedPort === port.path ? 'bg-blue-50 dark:bg-blue-900/30' : ''
                      }`}
                      onClick={() => {
                        setSelectedPort(port.path);
                        setIsPortDropdownOpen(false);
                      }}
                    >
                      {getPortIcon(port)}
                      <div className="flex-1">
                        <span className="text-gray-900 dark:text-white">{port.friendlyName}</span>
                      </div>
                      <span className={`text-xs px-2 py-0.5 rounded-full ${
                        getPortTypeLabel(port) === 'USB' 
                          ? 'bg-green-100 dark:bg-green-900/50 text-green-700 dark:text-green-300'
                          : getPortTypeLabel(port) === 'Bluetooth'
                          ? 'bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300'
                          : 'bg-gray-100 dark:bg-gray-600 text-gray-600 dark:text-gray-300'
                      }`}>
                        {getPortTypeLabel(port)}
                      </span>
                    </div>
                  ))}
                  {availablePorts.length === 0 && (
                    <div className="px-3 py-2 text-gray-500 dark:text-gray-400 text-sm italic">
                      No ports available
                    </div>
                  )}
                </div>
              )}
            </div>
            {deviceId && (
              <p className="text-xs text-green-600 mt-1">
                💾 Session ID: {deviceId}
              </p>
            )}
          </div>

          {/* Baud Rate */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Baud Rate</label>
            <select
              value={connectionSettings.baudRate}
              onChange={(e) => setConnectionSettings(prev => ({ ...prev, baudRate: parseInt(e.target.value) }))}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              disabled={isConnected}
            >
              <option value={9600}>9600</option>
              <option value={19200}>19200</option>
              <option value={38400}>38400</option>
              <option value={57600}>57600</option>
              <option value={115200}>115200</option>
            </select>
          </div>
        </div>

        {/* Connection Buttons */}
        <div className="flex space-x-4">
          <button
            onClick={handleTestConnection}
            disabled={isLoading || !selectedPort}
            className="btn btn-primary btn-md"
          >
            {isLoading ? 'Testing...' : 'Test Connection'}
          </button>
          
          {!isConnected ? (
            <button
              onClick={handleConnect}
              disabled={isLoading || !selectedPort}
              className="btn btn-success btn-md"
            >
              {isLoading ? 'Connecting...' : 'Connect'}
            </button>
          ) : (
            <button
              onClick={handleDisconnect}
              disabled={isLoading}
              className="btn btn-danger btn-md"
            >
              {isLoading ? 'Disconnecting...' : 'Disconnect'}
            </button>
          )}


        </div>
      </div>

      {/* Configuration Mode */}
      {isConnected && (
        <div className="bg-white dark:bg-gray-800 shadow rounded-lg p-6">
          <h2 className="text-lg font-medium text-gray-900 dark:text-white mb-4">Setup Configuration</h2>
          
          {/* Mode Selection */}
          <div className="flex space-x-4 mb-4">
            <label className="flex items-center">
              <input
                type="radio"
                value="template"
                checked={configMode === 'template'}
                onChange={(e) => setConfigMode(e.target.value)}
                className="mr-2"
              />
              Use Template
            </label>
            <label className="flex items-center">
              <input
                type="radio"
                value="custom"
                checked={configMode === 'custom'}
                onChange={(e) => setConfigMode(e.target.value)}
                className="mr-2"
              />
              Custom Configuration
            </label>
          </div>

          {/* Template Mode */}
          {configMode === 'template' && (
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Configuration Template</label>
                <select
                  value={selectedTemplate}
                  onChange={(e) => handleTemplateChange(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Choose configuration template</option>
                  {Object.entries(templates).map(([key, template]) => (
                    <option key={key} value={key}>
                      {template.name} - {template.description}
                    </option>
                  ))}
                </select>
              </div>

              {/* Template Variables */}
              {selectedTemplate && Object.keys(templateVariables).length > 0 && (
                <div className="bg-gray-50 dark:bg-gray-700 p-6 rounded-lg">
                  <h3 className="text-md font-medium text-gray-900 dark:text-white mb-4">Configuration Parameters</h3>
                  
                  {/* Basic Device Settings */}
                  <div className="mb-6">
                    <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">Device Settings</h4>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {['hostname', 'domain'].filter(key => Object.hasOwn(templateVariables, key)).map((varName) => (
                        <div key={varName}>
                          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1 capitalize">
                            {varName === 'hostname' ? 'Hostname' : 'Domain Name'}
                          </label>
                          <input
                            type="text"
                            value={templateVariables[varName]}
                            onChange={(e) => handleVariableChange(varName, e.target.value)}
                            placeholder={varName === 'hostname' ? 'SW-CORE-01' : 'company.local'}
                            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-800 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Security Settings */}
                  <div className="mb-6">
                    <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">Security Settings</h4>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {Object.hasOwn(templateVariables, 'rsa_key_size') && (
                        <div>
                          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            RSA Key Size
                          </label>
                          <select
                            value={templateVariables.rsa_key_size}
                            onChange={(e) => handleVariableChange('rsa_key_size', e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-800 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          >
                            <option value="1024">1024 bits</option>
                            <option value="2048">2048 bits (Recommended)</option>
                          </select>
                        </div>
                      )}

                      {['username', 'user_password'].filter(key => Object.hasOwn(templateVariables, key)).map((varName) => (
                        <div key={varName}>
                          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            {varName === 'username' && 'Username'}
                            {varName === 'user_password' && 'User Password'}
                          </label>
                          <input
                            type={varName.includes('password') ? 'password' : 'text'}
                            value={templateVariables[varName]}
                            onChange={(e) => handleVariableChange(varName, e.target.value)}
                            placeholder={
                              varName === 'username' ? 'admin' :
                              'Strong password for user'
                            }
                            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-800 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Management Interface Settings */}
                  {Object.hasOwn(templateVariables, 'management_interface') && (
                    <div className="mb-6">
                      <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">Management Interface</h4>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            Interface
                          </label>
                          <input
                            type="text"
                            value={templateVariables.management_interface}
                            onChange={(e) => handleVariableChange('management_interface', e.target.value)}
                            placeholder="vlan1, GigabitEthernet0/1, etc."
                            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-800 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                          <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                            Examples: vlan1, vlan10, GigabitEthernet0/1, FastEthernet0/1, Ethernet0/0
                          </p>
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            IP Configuration Method
                          </label>
                          <select
                            value={ipConfigMethod}
                            onChange={(e) => handleIPMethodChange(e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-800 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          >
                            <option value="manual">Manual IP Address</option>
                            <option value="dhcp">DHCP</option>
                          </select>
                        </div>
                      </div>

                      {/* IP Configuration Fields - Only show for manual */}
                      {ipConfigMethod === 'manual' && (
                        <div className="bg-blue-50 dark:bg-blue-900/30 p-4 rounded-md">
                          <h5 className="text-sm font-medium text-blue-900 dark:text-blue-300 mb-3">Manual IP Configuration</h5>
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                              <label className="block text-sm font-medium text-blue-700 dark:text-blue-400 mb-1">
                                IP Address
                              </label>
                              <input
                                type="text"
                                value={templateVariables.management_ip || ''}
                                onChange={(e) => handleVariableChange('management_ip', e.target.value)}
                                placeholder="192.168.1.10"
                                className="w-full px-3 py-2 border border-blue-300 dark:border-blue-700 dark:bg-gray-800 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                              />
                            </div>
                            <div>
                              <label className="block text-sm font-medium text-blue-700 dark:text-blue-400 mb-1">
                                Subnet Mask
                                <span className="text-xs text-blue-500 dark:text-blue-400 ml-2">(Support CIDR: /24, /25, etc.)</span>
                              </label>
                              <input
                                type="text"
                                value={templateVariables.management_mask || '/24'}
                                onChange={(e) => {
                                  let value = e.target.value;
                                  // Convert CIDR to subnet mask if needed
                                  if (value.startsWith('/')) {
                                    const converted = processSubnetInput(value);
                                    value = converted;
                                  }
                                  handleVariableChange('management_mask', value);
                                }}
                                placeholder="/24 or 255.255.255.0"
                                                                 className="w-full px-3 py-2 border border-blue-300 dark:border-blue-700 dark:bg-gray-800 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                               />
                               <div className="mt-2">
                                 <span className="text-xs text-blue-700 dark:text-blue-400 block mb-2">Quick Select CIDR (showing usable hosts):</span>
                                 <div className="grid grid-cols-8 gap-1">
                                   {Array.from({length: 22}, (_, i) => i + 10).map(num => {
                                     const cidr = `/${num}`;
                                     const hostCount = cidrToHostCount(cidr);
                                     const formatHostCount = (count) => {
                                       if (count >= 1000000) return `${(count / 1000000).toFixed(1)}M`;
                                       if (count >= 1000) return `${(count / 1000).toFixed(0)}K`;
                                       return count.toString();
                                     };
                                     return (
                                       <button
                                         key={cidr}
                                         type="button"
                                         onClick={() => {
                                           const converted = processSubnetInput(cidr);
                                           handleVariableChange('management_mask', converted);
                                         }}
                                         className="btn btn-outline-primary btn-sm text-xs"
                                         title={`${cidr} = ${cidrToSubnetMask(cidr)} | ${hostCount.toLocaleString()} usable hosts`}
                                       >
                                         <div className="text-center">
                                           <div className="font-mono">{cidr}</div>
                                           <div className="text-[10px] text-blue-500">{formatHostCount(hostCount)}h</div>
                                         </div>
                                       </button>
                                     )
                                   })}
                                 </div>
                                 <div className="mt-1 text-xs text-blue-500">
                                   "h" = usable hosts (excludes network/broadcast) | Hover for details
                                 </div>
                               </div>
                               <div className="mt-1 text-xs text-blue-600">
                                 Examples: <span className="font-mono">/24</span> = 255.255.255.0 (254 usable), <span className="font-mono">/30</span> = 255.255.255.252 (2 usable)
                                 {templateVariables.management_mask && templateVariables.management_mask.startsWith('/') && (
                                   <div className="mt-1 text-green-600 font-mono">
                                     ➜ {templateVariables.management_mask} = {cidrToSubnetMask(templateVariables.management_mask)} ({cidrToHostCount(templateVariables.management_mask)} usable hosts)
                                   </div>
                                 )}
                               </div>
                            </div>
                          </div>
                          <div className="mt-3 p-3 bg-blue-100 dark:bg-blue-900/30 rounded-md">
                            <p className="text-sm text-blue-800 dark:text-blue-300">
                              <strong>Note:</strong> No gateway configuration - device will be accessible only within local subnet
                            </p>
                          </div>
                        </div>
                      )}

                      {ipConfigMethod === 'dhcp' && (
                        <div className="bg-green-50 dark:bg-green-900/30 p-4 rounded-md">
                          <div className="flex items-center">
                            <div className="flex-shrink-0">
                              <span className="text-green-400 text-xl">✅</span>
                            </div>
                            <div className="ml-3">
                              <h5 className="text-sm font-medium text-green-800 dark:text-green-300">DHCP Configuration</h5>
                              <p className="text-sm text-green-700 dark:text-green-400">
                                Interface will automatically obtain IP address from DHCP server
                              </p>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Template Preview */}
                  <div className="mt-6">
                    <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Configuration Preview</h4>
                    <div className="bg-gray-900 rounded-lg p-4 max-h-64 overflow-auto code-scrollbar">
                      <pre className="text-green-400 text-sm font-mono whitespace-pre-wrap leading-relaxed">
                        {templates[selectedTemplate] && 
                          (() => {
                            // Create a preview config with IP method processing
                            let previewConfig = templates[selectedTemplate].config;
                            const vars = { ...templateVariables };
                            
                            // Process IP configuration for preview
                            if (vars.ip_method === 'dhcp') {
                              vars.interface_description_suffix = ' - DHCP';
                              vars.ip_configuration = ' ip address dhcp';
                            } else {
                              vars.interface_description_suffix = '';
                              // Convert CIDR to subnet mask for preview
                              let subnetMask = vars.management_mask || '{{management_mask}}';
                              if (subnetMask.startsWith('/')) {
                                subnetMask = cidrToSubnetMask(subnetMask) || subnetMask;
                              }
                              vars.ip_configuration = ` ip address ${vars.management_ip || '{{management_ip}}'} ${subnetMask}`;
                            }
                            
                            // Replace variables in preview
                            Object.entries(vars).forEach(([key, value]) => {
                              const placeholder = `{{${key}}}`;
                              previewConfig = previewConfig.replace(new RegExp(placeholder.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), value || `{{${key}}}`);
                            });
                            
                            const lines = previewConfig.split('\n');
                            return lines.slice(0, 20).join('\n') + 
                              (lines.length > 20 ? '\n... (truncated)' : '');
                          })()
                        }
                      </pre>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Custom Mode */}
          {configMode === 'custom' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Configuration Commands</label>
              <textarea
                value={customConfig}
                onChange={(e) => setCustomConfig(e.target.value)}
                placeholder="Enter Cisco IOS configuration commands, one per line..."
                rows={10}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
              />
            </div>
          )}

          {/* Apply Button */}
          <div className="mt-4">
            <button
              onClick={handleApplyConfiguration}
              disabled={isLoading || (!selectedTemplate && !customConfig)}
              className="btn btn-info btn-md"
            >
              {isLoading ? 'Applying Configuration...' : 'Apply Configuration'}
            </button>
          </div>
        </div>
      )}



      {/* Configuration Results */}
      {configResults && (
        <div className="bg-white dark:bg-gray-800 shadow rounded-lg p-6">
          <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-4">Configuration Results</h3>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
            <div className="bg-green-50 dark:bg-green-900/30 p-4 rounded-lg">
              <div className="text-2xl font-bold text-green-600 dark:text-green-400">{configResults.summary.successful}</div>
              <div className="text-sm text-green-700 dark:text-green-300">Successful Commands</div>
            </div>
            <div className="bg-red-50 dark:bg-red-900/30 p-4 rounded-lg">
              <div className="text-2xl font-bold text-red-600 dark:text-red-400">{configResults.summary.failed}</div>
              <div className="text-sm text-red-700 dark:text-red-300">Failed Commands</div>
            </div>
            <div className="bg-blue-50 dark:bg-blue-900/30 p-4 rounded-lg">
              <div className="text-2xl font-bold text-blue-600 dark:text-blue-400">{configResults.summary.successRate}%</div>
              <div className="text-sm text-blue-700 dark:text-blue-300">Success Rate</div>
            </div>
          </div>

          {/* Command Details */}
          <div className="space-y-2 max-h-64 overflow-auto custom-scrollbar">
            {configResults.results.map((result, index) => (
              <div
                key={index}
                className={`p-3 rounded ${
                  result.success ? 'bg-green-50 dark:bg-green-900/30 border-green-200 dark:border-green-700' : 'bg-red-50 dark:bg-red-900/30 border-red-200 dark:border-red-700'
                } border`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="font-mono text-sm font-semibold">{result.command}</span>
                  <div className="flex items-center space-x-2">
                    <span className={`text-xs px-2 py-1 rounded ${
                      result.success ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                    }`}>
                      #{result.sequence}
                    </span>
                    <span className={`text-sm ${result.success ? 'text-green-600' : 'text-red-600'}`}>
                      {result.success ? '✅' : '❌'}
                    </span>
                  </div>
                </div>
                {result.output && (
                  <div className="mt-2 p-2 bg-gray-100 dark:bg-gray-700 rounded text-sm font-mono text-gray-700 dark:text-gray-300 overflow-auto max-h-24">
                    {result.output.trim()}
                  </div>
                )}
                {result.error && (
                  <div className="mt-2 p-2 bg-red-100 dark:bg-red-900/50 rounded text-sm text-red-700 dark:text-red-300">
                    <strong>Error:</strong> {result.error}
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Full Configuration Output */}
          {configResults.fullOutput && (
            <div className="mt-6">
              <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">📋 Full Console Output</h4>
              <div className="bg-gray-900 rounded-lg p-4 max-h-96 overflow-auto code-scrollbar">
                <pre className="text-green-400 text-sm font-mono whitespace-pre-wrap leading-relaxed">
                  {configResults.fullOutput}
                </pre>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default ConsoleConfiguration; 